language: go

go:
  - 1.11.13
  - 1.10.8
  - 1.9.7
  - 1.8.7

notifications:
  email: false

before_install:
  - cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile
  - go get github.com/kr/pretty

script:
  - go build github.com/pkujhd/goloader/examples/loader
  - go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go
  - ./loader -o base.o -run main.main
